# Generated by Django 3.0.8 on 2020-07-30 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('share_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('share_amount', models.DecimalField(decimal_places=6, max_digits=13)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('trade_type', models.BooleanField(choices=[(True, 'Buy'), (False, 'Sell')])),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.StockSymbol')),
            ],
        ),
    ]
