# Generated by Django 3.0.8 on 2020-07-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stocktrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksymbol',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
