# Generated by Django 3.0.8 on 2020-08-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20200731_1014'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stocktrade',
            constraint=models.UniqueConstraint(fields=('stock', 'time', 'share_price', 'total_amount'), name='unique trade'),
        ),
    ]
