# Generated by Django 3.0.8 on 2020-08-04 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_brokerageservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktrade',
            name='brokerage_service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stocks.BrokerageService'),
            preserve_default=False,
        ),
    ]
